[[redirects]]
  from = "https://www.the14lights.com/*"
  to = "https://the14lights.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.the14lights.com/*"
  to = "https://the14lights.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://the14lights.com/*"
  to = "https://the14lights.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/platforms/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
